-- ─────────────────────────────────────────────────────────────────────────────
-- Supabase SQL — audits table
-- Run this in: Supabase Dashboard → SQL Editor → New query → Paste → Run
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.audits (
  -- Primary key: the UUID generated by runAudit() on the server
  id                    uuid         primary key,

  -- The sanitised AuditInput (no email / company ever stored)
  input                 jsonb        not null,

  -- Array of ToolRecommendation objects
  recommendations       jsonb        not null default '[]'::jsonb,

  -- Aggregated savings figures (stored as numeric for precision)
  total_monthly_savings numeric(12, 2) not null default 0,
  total_annual_savings  numeric(12, 2) not null default 0,

  -- True when totalMonthlySavings < $10 (team is well-optimised)
  is_optimal            boolean      not null default false,

  -- ISO-8601 timestamp; defaults to now() if the server omits it
  created_at            timestamptz  not null default now()
);

-- ─── Indexes ──────────────────────────────────────────────────────────────────

create index if not exists audits_created_at_idx
  on public.audits (created_at desc);

-- ─── Row-Level Security ───────────────────────────────────────────────────────

alter table public.audits enable row level security;

-- PUBLIC READ: anyone with the UUID can fetch the audit (shareable link)
create policy "Anyone can read audits by id"
  on public.audits
  for select
  using (true);

-- SERVER WRITE: the anon key used by the API route may insert rows
create policy "Anon can insert audits"
  on public.audits
  for insert
  to anon
  with check (true);

-- ─── Optional: automatic expiry cleanup ──────────────────────────────────────
-- Schedule via pg_cron or a Supabase Edge Function:
--
-- delete from public.audits where created_at < now() - interval '90 days';
